name: Job Output Task

on:
  workflow_dispatch:
  
jobs:
  get-date:
    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.date-step.outputs.today }}

    steps:
      - name: Get today's date
        id: date-step
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  print-date:
    runs-on: ubuntu-latest
    needs: get-date

    steps:
      - name: Print date from previous job
        run: echo "Today's date is ${{ needs.get-date.outputs.today }}"
        
                  